name:                haskell-app
version:             0.1.0.0
github:              "githubuser/haskell-app"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-app#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - http-client>=0.6.4.1
    - http-client-tls>=0.3.5.3
    - http-conduit>=2.3.7.3
    - http-types>=0.12.3
    - network-uri>=2.6.3.0
    - exceptions>=0.10.4
    - aeson>=1.4.7.0
    - bytestring>=0.10.10.0
    - text>=1.2.4.0
    - case-insensitive>=1.2.1.0
    - regex>=1.1.0.0
    - containers>=0.6.2.1
    - tagsoup==0.14.8
    - async==2.2.2

executables:
  haskell-app-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-app
    - warp==3.3.13
    - wai==3.2.2.1
    - http-types==0.12.3
    - exceptions>=0.10.4
    - bytestring>=0.10.10.0
    - text>=1.2.4.0
    - aeson>=1.4.7.0
    - mtl==2.2.2
    - containers>=0.6.2.1

tests:
  haskell-app-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-app
